apiVersion: v1
type: consumerMetricSetting
metricSettings:
  - metricName: "metric1"
    escalateIncidentAll: true
    thresholdAlertLowerBound: 15
    thresholdAlertUpperBound: 105
    thresholdAlertUpperBoundNegative: -20
    thresholdAlertLowerBoundNegative: -5
    thresholdNoAlertLowerBound: 50
    thresholdNoAlertUpperBound: 75
    thresholdNoAlertLowerBoundNegative: 20
    thresholdNoAlertUpperBoundNegative: 40

  - metricName: "metric2"
    escalateIncidentAll: true
    thresholdAlertLowerBound: 15
    thresholdAlertUpperBound: 105
    thresholdAlertUpperBoundNegative: -20
    thresholdAlertLowerBoundNegative: -5
    thresholdNoAlertLowerBound: 50
    thresholdNoAlertUpperBound: 75
    thresholdNoAlertLowerBoundNegative: 20
    thresholdNoAlertUpperBoundNegative: 40